### ISSUE TITLE
FTBS on Debian/testing with gfortran 10.2.0

### ISSUE THREAD

**Issue by Trophime** [madebr/pyOpt#11]
Hi,
I'm trying to rebuild pyopt on Debian/Testing.
I run into the following error:

```
gfortran:f77: pyOpt/pyALGENCAN/source/evalal.f
gfortran:f77: pyOpt/pyALGENCAN/source/extrap.f
pyOpt/pyALGENCAN/source/evalal.f:408:35:

  408 |               call sevalgjacp(n,xp,gp,m,dpdcp,nalp,'T',gotj,inform)
      |                                   1
......
  802 |           call sevalgjacp(n,x,dum,m,ap,ptmp,'j',gotj,inform)
      |                              2     
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-1)
pyOpt/pyALGENCAN/source/evalal.f:112:34:

  112 |               call sevalgjacp(n,x,g,m,p,nl,'T',gotj,inform)
      |                                  1
......
  802 |           call sevalgjacp(n,x,dum,m,ap,ptmp,'j',gotj,inform)
      |                              2    
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-1)
```

**Comment by madebr** [comment]
I suppose this is using gcc 10.
https://gcc.gnu.org/gcc-10/porting_to.html

I'm currently using gcc9, but will look into this once I upgrade.

**Comment by Trophime** [comment]
Indeed it compiles like a charm with gfortran-9 ;)

**Comment by madebr** [comment]
I pushed fixes to the fortran sources in the following branch: https://github.com/madebr/pyOpt/tree/gfortran-11-fixes.
It would be nice if you could test + review this patch.

//cc @mayou36  for extra review

**Comment by mayou36** [comment]
Can you maybe make a RP? So it's easier to review

**Comment by madebr** [comment]
> Can you maybe make a RP? So it's easier to review

Good idea. That's where PR's are for :smile: 
See #19
