### ISSUE TITLE
mpi4py

### ISSUE THREAD

**Issue by zhujun98** [madebr/pyOpt#2]
May I ask why openmpi.mpi4py instead of just mpi4py?

How can I install openmpi module?

Thanks a lot!

**Comment by madebr** [comment]
At the time, I didn't get mpi4py to compile/install. I just tried again and I succeeded.
I guess e96f941faa3fcfbfac9f6543a45bff5afe60c9ba can be reverted.

**Comment by zhujun98** [comment]
Thank you for your quick reply!
